services:
  - type: web
    name: love-letter-website
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
